### ISSUE TITLE
External Id Support

### ISSUE THREAD

**Issue by ryanbrainard** [ForceCLI/force#12]
Force.com records can have external ids, which are essentially alternate (usually) unique keys for getting, inserting, updating, and upserting records. For example:
- [Retrieve a Record Using an External ID](http://www.salesforce.com/us/developer/docs/api_rest/Content/using_resources_retrieve_with_externalid.htm)
- [Insert or Update (Upsert) a Record Using an External ID](http://www.salesforce.com/us/developer/docs/api_rest/Content/dome_upsert.htm)

In addition to the upserts, explicit inserts and updates also support external ids, but doesn't look like its documented. This would allow users to do things like this instead of using Salesforce IDs:

```
$ force record get User username:user@company.com
$ force record update User username:user@company.com LastName:Smith
etc
```

**Comment by cwarden** [comment]
This was implemented in #63.
