### ISSUE TITLE
No Binaries, Build Broken

### ISSUE THREAD

**Issue by DavidCDean** [ForceCLI/force#130]
The build process for OSX fails with the following...

../github.com/ddollar/config/windows.go:8: (*Config).homeDirectory redeclared in this block
    previous declaration at ../github.com/ddollar/config/posix.go:9

I did find a working link for the precompiled binary, but the build seems to be broken.

**Comment by dcarroll** [comment]
Its not a fix. There is a compile directive that should include on or the other depending on what OS you are compiling on. 

Dave Carroll
