### ISSUE TITLE
Pre-compiled OSX-64bit download link is down

### ISSUE THREAD

**Issue by westhechiang** [ForceCLI/force#141]
Error says 'Internal Error'.

**Comment by dcarroll** [comment]
Try refreshing the page.  There is some minor error on the web site.

On Mon, Feb 23, 2015 at 9:28 AM, westhechiang <notifications@github.com>
wrote:

> Error says 'Internal Error'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/141>.
>



-- 
Thanks,
Dave

**Comment by westhechiang** [comment]
Nice, thanks for the quick response.
