### ISSUE TITLE
`force query` only returns 1000 records

### ISSUE THREAD

**Issue by abhikp** [ForceCLI/force#146]
Is there a way to get all records?

**Comment by abhikp** [comment]
It looks like the culprit is formatting in csv. I get the expected amount of records with force query and a number much less with force query --format:csv

**Comment by jpmonette** [comment]
@abhikp I've been trying that one, but there is no limit other than the standard salesforce governor limit.

Do you still have the issue @abhikp?

**Comment by cwarden** [comment]
This was fixed in #175.
