### ISSUE TITLE
"force update" command throws error

### ISSUE THREAD

**Issue by ImJohnMDaniel** [ForceCLI/force#197]
Execution of "force update" gives the following error: "ERROR: no such from"

Using version v0.22.30 on MacOS 10.10.5.

Thoughts?

**Comment by dcarroll** [comment]
Yeah, that feature doesn't work. Sorry.

On Tue, Aug 18, 2015 at 4:08 PM, John M. Daniel <notifications@github.com>
wrote:

> Execution of "force update" gives the following error: "ERROR: no such
> from"
>
> Using version v0.22.30 on MacOS 10.10.5.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/197>.
>



-- 
Thanks,
Dave

**Comment by cwarden** [comment]
I opened #471 to remove the update command.

**Comment by cwarden** [comment]
Removed the broken update command in #471.
