### ISSUE TITLE
REQUEST: live stream logs

### ISSUE THREAD

**Issue by liratanak** [ForceCLI/force#200]
Hi,

I see `force log` was added and nice :-)
Thanks

I think it would be better if we can do something like `force log tail | grep USER`
What do you think ?

Sincerely,
Liratanak

**Comment by jpmonette** [comment]
@liratanak What do you mean? You can do `force log [logId] | tail | grep USER` if needed.

What is your use case / example?

**Comment by liratanak** [comment]
I can simply say "Live stream logs".
I did create a node package for this reason, https://github.com/liratanak/sflog
But it was actually drain the api usage even if I already use the tooling api.

You can take a look at that repo; and you'll what I am really mean.

Thanks

**Comment by jpmonette** [comment]
Oh. I thought about that too at some point, but sadly, there is no way to achieve this without polling the API. Also, Streaming API does not support this object.

Thanks for sharing your project - I'll have a look at it.

**Comment by dcarroll** [comment]
I'm looking at using streaming api like the Dev console. Just starting an
investigation to find a cometd go lib.

Dave Carroll

On Oct 22, 2015, at 5:14 AM, Jean-Philippe Monette <notifications@github.com>
wrote:

Oh. I thought about that too at some point, but sadly, there is no way to
achieve this without polling the API. Also, Streaming API does not support
this object.

Thanks for sharing your project - I'll have a look at it.

—
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/issues/200#issuecomment-150202608>.

**Comment by cwarden** [comment]
Something like `force stream /systemTopic/Logging` would be nice.  If it outputs a stream of events from the Streaming API, you could use it in a pipeline to tail the logs, e.g.
```
force stream /systemTopic/Logging | grep -Po '07L\w+' | xargs -I {} force log {}
```

**Comment by jpmonette** [comment]
@cwarden That is awesome! I'll have a look at it.

**Comment by cwarden** [comment]
Subscribing to the `/systemTopic/Logging` topic is the approach I used in [Apex Flame](http://www.octoberswimmer.com/apex-flame/) to keep the table of log records up to date.  You get `created` events like:
```
{
  "event": {
    "type": "created",
    "createdDate": "2015-10-22T16:11:56.000+0000"
  },
  "sobject": {
    "Id": "07L37000000WwFYEA0"
  }
}
```

**Comment by cwarden** [comment]
If someone wants to implement this, subscribing to `/systemTopic/Logging` only [works up until v36.0](https://salesforce.stackexchange.com/q/165381/240).

**Comment by cwarden** [comment]
`sf apex tail log` still uses `/cometd/36.0` to subscribe to `/systemTopic/Logging` as of version  1.73.0.
