### ISSUE TITLE
Simple count() query doesn't seem to work

### ISSUE THREAD

**Issue by scottpersinger** [ForceCLI/force#21]
```
(venv)spersinger-ltm:Downloads spersinger$ ./force query "select count() from Lead"

```

Query returns the count in the totalSize attribute of the result. Would be nice to show this from the cli.

**Comment by jungar** [comment]
I'm still seeing this in v0.22.66, at least for PermissionSetAssignment object:

$ force version
v0.22.66

force query "SELECT Id FROM PermissionSetAssignment WHERE PermissionSetId = 'XXXX0000000XXX'"
// < snip! >
 (1498 records)

force query "SELECT Count() FROM PermissionSetAssignment WHERE PermissionSetId = 'XXXX0000000XXX'"
 (0 records)

**Comment by Soundsphere** [comment]
I'm facing the same issue on all Objects in our Org on 22.67 as well. A regular query returns results, but count() always shows 0 records.

**Comment by cwarden** [comment]
Does `COUNT(Id)` work?

**Comment by Soundsphere** [comment]
Yes, count(Id) does return the expected result, albeit in a different format than the count() query
