### ISSUE TITLE
Discussion: Finalize design standards for v1

### ISSUE THREAD

**Issue by ViViDboarder** [ForceCLI/force#223]
This is an attempt at what was discussed in #218. We can evolve this issue as the discussion progresses.

For a v1.0 release, it is prudent to have a consistent API design finalized that future implementations will be able to follow. This will allow any users after v1.0 to not have to worry about 1.x releases ever breaking their existing feature set or interfaces. To provide this guarantee, common command structure, flags, and arguments should be agreed upon and then made consistent throughout the application.

To get the party started, here is my proposal:

I propose we follow a command/subcommand design (this already exists) that will allow us to extend with new features and plugins that could even be independent of this project. Flags and options should be optional and standard default behavior should be intuitive and discoverable.

We can debate individual command flags and arg changes through reviews for each command, but here are a few examples of changes that I think may benefit from this design.
### login

```
force login [-u | --username <username>] [-p | --password <password>] [<instance>]
```

The help text can clarify default instance as well as what the short abbreviated instances are. This removes the need to specify mandatory options.

This is the simplest I can think of, but perhaps it's worth mimicking the idea of git remotes as I did in [abuse-the-force](https://github.com/ViViDboarder/abuse-the-force)
### push

```
force push [-t | --type] <metadata_type> [-n | --name] <metadata_name>
force push [-t | --type] <metadata_type> --all
force push ./path/to/file.ext
```

Since metadata type pushes will require two parameters, rather than using ambiguous positional arguments, option flags are used. This frees up what to do with positional arguments. I suggest using a path to file to provide easy use on the terminal or integration with other tools (`vim`, `xargs`, `find`).

---

Once we agree on this I can get started on a PR and we can discuss how to implement a similar pattern for the other commands.

**Comment by dcarroll** [comment]
This looks like the direction I was heading and will provide forward as
well as backward compatibility.  The trick will be to determine what
arguments get flags and which are assumed.  I like the idea of "resources",
paths or uris as the last and unflagged arguments.  This seems consistent
with a lot of unix commands.

I am behind this approach.  Do we need additional agreement/debate?

On Wed, Dec 2, 2015 at 2:18 PM, Ian <notifications@github.com> wrote:

> This is an attempt at what was discussed in #218
> <https://github.com/heroku/force/issues/218>. We can evolve this issue as
> the discussion progresses.
>
> For a v1.0 release, it is prudent to have a consistent API design
> finalized that future implementations will be able to follow. This will
> allow any users after v1.0 to not have to worry about 1.x releases ever
> breaking their existing feature set or interfaces. To provide this
> guarantee, common command structure, flags, and arguments should be agreed
> upon and then made consistent throughout the application.
>
> To get the party started, here is my proposal:
>
> I propose we follow a command/subcommand design (this already exists) that
> will allow us to extend with new features and plugins that could even be
> independent of this project. Flags and options should be optional and
> standard default behavior should be intuitive and discoverable.
>
> We can debate individual command flags and arg changes through reviews for
> each command, but here are a few examples of changes that I think may
> benefit from this design.
> login
>
> force login [-u | --username <username>] [-p | --password <password>] [<instance>]
>
> The help text can clarify default instance as well as what the short
> abbreviated instances are. This removes the need to specify mandatory
> options.
>
> This is the simplest I can think of, but perhaps it's worth mimicking the
> idea of git remotes as I did in abuse-the-force
> <https://github.com/ViViDboarder/abuse-the-force>
> push
>
> force push [-t | --type] <metadata_type> [-n | --name] <metadata_name>
> force push [-t | --type] <metadata_type> --all
> force push ./path/to/file.ext
>
> Since metadata type pushes will require two parameters, rather than using
> ambiguous positional arguments, option flags are used. This frees up what
> to do with positional arguments. I suggest using a path to file to provide
> easy use on the terminal or integration with other tools (vim, xargs, find
> ).
> ------------------------------
>
> Once we agree on this I can get started on a PR and we can discuss how to
> implement a similar pattern for the other commands.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/223>.
>



-- 
Thanks,
Dave

**Comment by ViViDboarder** [comment]
Probably not. @cwarden @sebastianclaros, since you were involved in the previous ticket discussion any objections?

**Comment by cwarden** [comment]
I'm not clear exactly what's being proposed.  Just that the parameters for `login` and `push` be modified as described?  (Part of the proposed `push` changes are in #222).

`login` and `push` both already use [flag](https://golang.org/pkg/flag/) for parameter passing so those are probably a good place to start since the proposed changes could be made with relatively minor modifications.

Are we adopting ginkgo for these and future changes?  If we follow the convention of using a separate package for the ginkgo specs, we might need to do a decent amount of refactoring to write tests for the parameter parsing since the results of the parsing are stored in unexported variables.  Any thoughts on the best approach?

**Comment by dcarroll** [comment]
Food for thought.  I will be taking time away from my day job over Dec and Jan to devote some time to this project.  I am seriously considering a considerable re-write of the CLI to get to a v1.0.

I have been looking at the source for the heroku toolbelt here https://github.com/heroku/heroku-cli.  The heroku toolbelt is a cli that supports plugins and is self-updating and implements some interesting patterns that could be used here. In particular is the topic/command pattern.  Topics are "categories" that have related functionality at the command level.

For instance, in the case of the force cli, there several commands related to authentication and specific accounts (login, logout, account etc).  With the topic/command pattern these would be lumped under an auth topic with a specific command for each.

`force auth:login 

force auth:logout`

A plugin, written in node.js would define a new topic and zero or more commands.  

Ultimately, this is relevant to create a solid core that is reliable, has tests, and allows for additions/changes to be plugged in by the end user.  

If you want to see how the Heroku Toolbelt works check out the project linked above and the heroku/heroku-docker plugin available both on github and through npm.

**Comment by cwarden** [comment]
I've completed the major clean-ups I wanted to do in preparation for 1.0 in #624 and #657.
