### ISSUE TITLE
Support "queryAll" endpoint in `force query`

### ISSUE THREAD

**Issue by chexxor** [ForceCLI/force#237]
I am trying to query deleted records using the "ALL ROWS" query modifier using `force query`, but I get the "ERROR: ALL ROWS not allowed in this context" error.

To get around this, my query needs to be sent to the "queryAll" endpoint.

It seems like a simple contribution, so I tried to do it myself. I followed the instructions in the "hacking" section to clone this repo using "go get", but I got x509/CA Certificate errors (I'm on OS X) and gave up. I'll post this as a feature request for now.

**Comment by cwarden** [comment]
Implemented in #469.  Use `force query --all "SELECT ..."`
