### ISSUE TITLE
force fetch does not update the package.xml file in a second run

### ISSUE THREAD

**Issue by joanbarros** [ForceCLI/force#268]
The `force fetch` sub-command does not update the _package.xml_ if one already exists.
# Reproduction
1. run `force fetch -t ApexClass -n SomeClass`
2. run `cat metadata/package.xml` and mind the classes present.
3. run `force fetch -t ApexClass -n SomeOtherClass`.
4. run `cat metadata/package.xml` and notice that SomOtherClass was not added.

**Comment by cwarden** [comment]
This is by design.  `force-md package add -t ApexClass -n SomeOtherClass src/package.xml` can be used to update `package.xml`.
