### ISSUE TITLE
force trace list - error in version v0.22.55

### ISSUE THREAD

**Issue by thhsfdc** [ForceCLI/force#285]
Hi,

running this:
force trace list
ERROR: No such relation 'Scope' on entity 'TraceFlag'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

whilst using the v0.22.51 brings a valid result

**Comment by cwarden** [comment]
This should be fixed by c0cc076f5034f24ae1203d8894ffc163aa43c851, which I've been using since January, but I just rebased it against master so I haven't fully tested it.

**Comment by cwarden** [comment]
This was fixed in #349.
