### ISSUE TITLE
DESIGN: Push command

### ISSUE THREAD

**Issue by ViViDboarder** [ForceCLI/force#289]
It seems that push.go has grown to be quite complicated. @dcarroll and I were talking in Slack and I'm looking to do a bit of a refactor (round 2!) to simplify things out again.

I can try to keep this updated as the discussion progresses, but I want to keep track of requirements and proposals here.
### Requirements
- push by file path should not be dependent on the package directory name: `src`, or `metadata`, or even `foo` should all be valid. This allows supporting multiple packages
- Should be able to push packaged or unpackaged code by both file (described above) or metadata name
- Metadata types should be case insensitive
### Proposals
- All files should be pushed by their paths, even if provided by metadata
- The metadata handling should be done before passing paths into the push by path methods
- A "package" option should allow specifying pushing files from a pre-packaged directory. If not specified, `GetSrcDirectory` will be used to find a valid package. (Side note, maybe rename to `GetUnpackagedRoot`)
- To support these changes and provide easier support for future directory names, pushing by file should not require a whitelisted root directory. Instead the root can be found by walking up from a metadata file

That's all I have. If you have a use-case that I didn't cover, let me know.

**Comment by cwarden** [comment]
See #657
