### ISSUE TITLE
DESIGN: Project config

### ISSUE THREAD

**Issue by ViViDboarder** [ForceCLI/force#290]
This is based on a conversation in Slack as well. I don't have very many details here, but I'll try to outline.

There are certain settings that would be useful to store at a project level. And, possibly, in a shell environment variable. To do this we need to define a hierarchy of config values. `~/.config/force/config.json`, `.force-config.json`, and finally environment variables in the form of `FORCE_MYVAR`. Something like that.

Anyone have any thoughts on how to proceed?

**Comment by dcarroll** [comment]
What are the values that need to persist between sessions?

**Comment by orospakr** [comment]
In #287, I added a feature for project-level config (parameterized by the environment you're talking to) in a JSON format right in your source directory.  I documented it in the README :)
