### ISSUE TITLE
Using force cli in Mac OSx El Capitan with regular user raises exception

### ISSUE THREAD

**Issue by inakirzabalegui** [ForceCLI/force#291]
If I invoke force cli with root user (sudo) it works but if I try to use it with regular user I always obtain exceptions. It allows me to login althought actually it is not logged in. If I try anything else afterwards I have an exception, each command different one. it looks like force assumes I am logged in and when it tries to acces the login info it points to null in memory. 

See an example:

jzabalegui@jzabalegui-ltm1:~/bin$ ./force login -u=inaki.r.zabalegui@fleeceme.com
Password: 
Save login was  ok
Logged in as 'inaki.r.zabalegui@fleeceme.com' (API v36.0)
jzabalegui@jzabalegui-ltm1:~/bin$ ./force active
-  - ns:
  jzabalegui@jzabalegui-ltm1:~/bin$ ./force logins
  no logins
  jzabalegui@jzabalegui-ltm1:~/bin$ ./force fetch -t Aura
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal 0xb code=0x1 addr=0x0 pc=0x2bc37]

goroutine 1 [running]:
panic(0x4f44c0, 0xc8200100b0)
    /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
main.(_Force).GetAuraBundlesList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/travis/gopath/src/github.com/heroku/force/force.go:480 +0x367
main.(_Force).GetAuraBundles(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/travis/gopath/src/github.com/heroku/force/force.go:428 +0x8c
main.runFetchAura2(0x8524a0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/heroku/force/fetch.go:84 +0x80
main.runFetch(0x8524a0, 0xc82000a1f0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/heroku/force/fetch.go:203 +0x202d
main.main()
    /home/travis/gopath/src/github.com/heroku/force/main.go:56 +0x2f2

**Comment by cwarden** [comment]
Check the permissions on `~/.force/current/account`.  Is it only readable by root?

**Comment by inakirzabalegui** [comment]
Thanks, that was the reason. Permissions in the hidden folder were wrong.
