### ISSUE TITLE
binary links without the proper extensions

### ISSUE THREAD

**Issue by caridy** [ForceCLI/force#292]
The links from the release page, and the link from the HOME Page, do not have the right extensions, e.g.:

https://s3-us-west-2.amazonaws.com/force-cli/heroku/force/v0.22.57/darwin-amd64/force

As a result, I get a 12M files that is recognized as a text file in OS X.

note: I think debian/ubuntu links has the same issue.

**Comment by dcarroll** [comment]
There is no extension for Mac or Linux.  If you know how to ensure that the
permissions contain "x" executable I'd be happy to ode.

You just need to chod +x the file and put a symlink in your path somewhere
like /usr/local/bin or /usr/bin

Dave


On Fri, May 27, 2016 at 4:19 PM, Caridy Patiño <notifications@github.com>
wrote:

> The links from the release page, and the link from the HOME Page, do not
> have the right extensions, e.g.:
>
>
> https://s3-us-west-2.amazonaws.com/force-cli/heroku/force/v0.22.57/darwin-amd64/force
>
> As a result, I get a 12M files that is recognized as a text file in OS X.
>
> note: I think debian/ubuntu links has the same issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/heroku/force/issues/292>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAHGHkqkm475DsaBZjgtTQzeXIZE1slBks5qF3wXgaJpZM4Io7mr>
> .
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
Also, if you download the windows version it does have an .exe extension.

**Comment by caridy** [comment]
alright, in that case we should probably add some details in a wiki page or something. alternative we can add some proper installation steps.

**Comment by cwarden** [comment]
Releases are no in zip files so that when extracted, the files are executable.  Windows binary is named force.exe.
