### ISSUE TITLE
force export fails to create "metadata" folder, also fails to create the specific folder name

### ISSUE THREAD

**Issue by diligent176** [ForceCLI/force#296]
The inline help for **force export** says you can specify the directory name.
E.g.  _force export dir-name_

This does not work.  It always exports to "metadata".  And now, in the latest [0.22.57] it is failing to even create the "metadata" directory.  You must manually create metadata directory or the entire process fails at the very end.

> Error obtaining root directory
> ERROR: GetFileAttributesEx C:\agit\standalone\metadata: The system cannot find the file specified.

**Comment by j-fischer** [comment]
I have the same issue, version 0.22.57 on Windows 10 version 1607.

**Comment by pranayjswl007** [comment]
I have same issue. With export and fetch.

**Comment by cwarden** [comment]
Fixed in 26e083b7d3d21a220a87d274747da7a3079b88d7
