### ISSUE TITLE
Reg. command option Export/Import

### ISSUE THREAD

**Issue by sankaran1984** [ForceCLI/force#306]
I feel command option Export & Import is misleading. I would expect 'Import' to download artifacts to local directory, rather than other way around. 
Can you please let me know if there's any real reason to be designed that way.

**Comment by cwarden** [comment]
Commands are relative to the org, `export`ing metadata from the org, `import`ing metadata into the org.  These are consistent with the data commands, e.g. `bulk insert`ing data into the org.
