### ISSUE TITLE
force export error

### ISSUE THREAD

**Issue by desaikarna** [ForceCLI/force#308]
Hi,

I am getting following error while running 'force export' command

> runtime: VirtualAlloc of 2097152 bytes failed with errno=487
> fatal error: runtime: cannot map pages in arena address space
> 
> runtime stack:
> runtime.throw(0x8d6cc0, 0x30)
>         /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530
> +0x7f
> runtime.sysMap(0x52d30000, 0x200000, 0x32a3fd01, 0xac0918)
>         /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/mem_windows.g
> o:116 +0xf9

**Comment by cwarden** [comment]
Fixed in v0.22.60 (26e083b7d3d21a220a87d274747da7a3079b88d7).
