### ISSUE TITLE
PK Chunking Header with Force Cli

### ISSUE THREAD

**Issue by mokchenda** [ForceCLI/force#312]
Is there a way to support PK Chunking Header with force cli ?
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/async_api_headers_enable_pk_chunking.htm

**Comment by cwarden** [comment]
I've opened #536 with initial support for PK Chunking.

**Comment by cwarden** [comment]
This is included in v0.25.0.
