### ISSUE TITLE
wrong API version while exporting

### ISSUE THREAD

**Issue by tpanigrahi** [ForceCLI/force#370]
While using force export from a winter 17 env, package.xml contains version as 37 in stead of 38

**Comment by KThompso** [comment]
I believe the API version in the the generated package.xml file is set by the current API version in the force cli.  You can set this value to 38.0 by running:

`$ force apiversion 38.0`

Note that you have to be logged in for this to persist, and that it's defined for each account.  The default API version is currently set to 37.0, perhaps it should be updated to reflect the current version 39.0.

**Comment by sfllaw** [comment]
#410 has updated the default to 39.0.

**Comment by cwarden** [comment]
Confirmed that the current api version for the session, as set by `force apiversion` is used for `force export`.  This may have been fixed in 1cb643be795175f5509dc4b0c485db2473a42508 (v0.22.72).
