### ISSUE TITLE
Add ability to set FLS when adding a field

### ISSUE THREAD

**Issue by danieljpeter** [ForceCLI/force#38]
A common use case is adding field(s) to sandbox, setting the FLS by profile with the UI, then writing code that use those fields.  Then you need to re-add the fields to prod before deploying code.  Can be done with change sets or other methods.  Would be awesome if force CLI gave you a quick way to say, add a custom field and set the FLS to be read/write on these XX profiles, read on these XX profiles, and no access on these XX profiles by a list of some sort.

Thanks!

**Comment by cwarden** [comment]
Closing as out of scope.  See `force-md` for editing field permissions in profile and permission set metadata.
