### ISSUE TITLE
Deployment failing due to code coverage, CLI reports success

### ISSUE THREAD

**Issue by normanpride** [ForceCLI/force#399]
We are facing an issue with deployments that are going to a new sandbox. If we try to deploy code without the test classes, the CLI will tell us the deployment succeeded ( 0 test failures, 0 issues in metadata ) while the instance will let us know that code coverage was not enough to deploy. This results in a build that passes according to the CLI, but fails according to the instance.

force push -r -l RunLocalTests -i -c <file list>

Same issue without -c as well.

**Comment by dcarroll** [comment]
Thanks Norman, will take a look when I get the chance, may be just not handling the response properly.

**Comment by cwarden** [comment]
I opened #420 to address this.  `force push` will report coverage warnings.  If `-r` is used, and code coverage prevents deployment, `force push` will exit with failure.

**Comment by cwarden** [comment]
@normanpride, does the change included in v0.22.75 fix the problem for you?

**Comment by cwarden** [comment]
Please re-open if it's still an issue.
