### ISSUE TITLE
Bash Auto Complete for force cli

### ISSUE THREAD

**Issue by synle** [ForceCLI/force#404]
Over the weekend, I wrote a bash function that provide TAB completion for force cli, I wonder if it's worthy to be integrated into this repo wiki.

This is the git repo
https://github.com/synle/force-cli-autocomplete

Below is a screenshot of what it does
![screenshot](https://cloud.githubusercontent.com/assets/3792401/25305420/9638cf68-272f-11e7-8ad0-99cdfc037c48.png)

**Comment by cwarden** [comment]
This is great.  Thanks, @synle.

One issue I've found is that it breaks filename completion for `force push`.  I'd like to be able to do e.g. `force push -ch<TAB> src/cl<TAB>/MyCl<TAB>` to complete `force push -checkonly src/classes/MyClass.cls`.

**Comment by synle** [comment]
@cwarden Thanks. I'll look into the issue

**Comment by synle** [comment]
@cwarden I added the nospace option `complete -o nospace -F _force_cli_completion force`.

It should work now, let me know if you have any question

**Comment by cwarden** [comment]
Autocompletion now supported with `force completion`, e.g. `source <(force completion bash)`.
