### ISSUE TITLE
Force Push StaticResource hangs

### ISSUE THREAD

**Issue by synle** [ForceCLI/force#407]
It keeps saying to retry in 5 secs, I did a little digging and found that it might run into an infinite loop. This is the error I received

`Failed to create createContainerMember for containerId=<some_ids>: This container member belongs to a container that currently has an unfinished save request with deploymentId=<some_ids>. You may not modify any members in this container until it completes.: Metadata Container ID`

**Comment by dcarroll** [comment]
Great catch Sy.  I'm having trouble carving out time to track these down.
Can you take a look and recommend a fix?
