### ISSUE TITLE
Can not push single custom field

### ISSUE THREAD

**Issue by yurybond** [ForceCLI/force#409]
When I try to deploy a single custom field using the following command:

`force push -t CustomField -n Account.DefaultTeamlead__c`

I gen an error below:

> Validating and deploying push...
> ERROR: No folders that contain CustomField metadata could be found.

Is it something currently impossible or this is a bug?

**Comment by dcarroll** [comment]
If you are trying to create a Custom field you should use the force field
create command.

**Comment by yurybond** [comment]
I am actually trying to move some fields from one org to another. 
I already have this field specified in Account.object metadata file.

So my case is to fetch a group of fields from one org - which is working fine with `force fetch`
And then deploy this fields to another org - i am tried to use `force push`, probably there is another way to do it

**Comment by yurybond** [comment]
Hi Dave,

Is there any ability to push metadata that does not have separate file like CustomField or ValidationRule

**Comment by yurybond** [comment]
Use create custom field instead of push as a workaround
