### ISSUE TITLE
Can not push object with latest build

### ISSUE THREAD

**Issue by yurybond** [ForceCLI/force#410]
When try to push custom object with custom picklists

`force push -t CustomObject -n SomeObjectWithPicklist__c`

I get the following error

> ERROR with SomeObjectWithPicklist__c.CustomPickList__c, line ###
> Property 'valueSet' not valid in version 37.0

I compiled force cli for windows from the latest code in repo.

**Comment by dcarroll** [comment]
37.0 is the API version  Make sure that valueSet is in the version of the
API that you are using with the CLI. You can set the API version using the
apiVersion command.

**Comment by yurybond** [comment]
Yes, the valueSet is the new node in salesforce object metadata for picklist-fields which is not valid for  version 37.0

I tried to update version to 38.0 and 39.0 (current) with `force apiversion 39.0` command-line
but
still getting the error I mentioned above

> ERROR with SomeObjectWithPicklist__c.CustomPickList__c, line ###
> Property 'valueSet' not valid in version 37.0

It looks like manual changing of version is not applied with deployment, despite this if I check version with `force apiversion` it returns the correct one (that I manually set)

**Comment by sfllaw** [comment]
I can confirm this issue. We recently migrated to using the Ant Migration Tool v39.0 and it snapshots files that are incompatible with force CLI, which only understands v37.0.

**Comment by dcarroll** [comment]
I have done a new release to default the version to 39.0.

**Comment by sfllaw** [comment]
Master works now. afdc2b7 and e55603c seem to have done the trick. Thanks!

**Comment by sfllaw** [comment]
Although it is worrisome that `force apiversion` doesn't actually set the API version correctly.

**Comment by floyd-may** [comment]
The fact that we can't control the API version of the `push` command could potentially be a big deal for us. Any relative size estimate for how big of a deal this is to fix?

**Comment by dcarroll** [comment]
Not huge

**Comment by sfllaw** [comment]
@dcarroll: Please review ⬆️ which should fix this issue.

**Comment by dcarroll** [comment]
Thanks for the PR Simon, will review soon.

**Comment by yurybond** [comment]
Fixed.
