### ISSUE TITLE
force bulk insert field not found

### ISSUE THREAD

**Issue by jeremy-walsh-vgh** [ForceCLI/force#413]
Hey guys, I have an object Call_Report__c that has a field Report_Date__c.  When I do a bulk operation via the force cli I get a failed batch with status:

```
$ force version
v0.22.72
$ force bulk insert Call_Report__c callReport.sfdcImport.csv
$ force bulk batch 750C0000005zdEYIAY 751C0000008zTtxIAE

Id 			751C0000008zTtxIAE
JobId 			750C0000005zdEYIAY
State 			Failed
CreatedDate 		2017-05-24T15:59:13.000Z
SystemModstamp 		2017-05-24T15:59:13.000Z
NumberRecordsProcessed  0

<Job.Batch.StateMessage>InvalidBatch : Field name not found : Report_Date__c</>
```

When I take that same file and import via demandtools/dataloader.io, it works without issue.  I thought it might be case sensitivity but that doesn't seem to be the issue.  I'm matching cases against the output on the field detail page, and the info returned by the object metadata tool in force.com workbench.

**Comment by cwarden** [comment]
Does `force query "SELECT Report_Date__c FROM Call_Report__c LIMIT 1"` work?

**Comment by cwarden** [comment]
Closed for inactivity.
