### ISSUE TITLE
force push keeps failing with error: Could not add the following files

### ISSUE THREAD

**Issue by chirag64** [ForceCLI/force#417]
I tried `force push` with multiple parameters, but it keeps failing for me with the same error:

`force push -t StaticResource -f metadata/staticresources/`
ERROR: Could not add the following files:
 {}
%!(EXTRA string=metadata/staticresources/)

`force push -t AuraDefinitionBundle -f metadata/aura/`
ERROR: Could not add the following files:
 {}
%!(EXTRA string=metadata/aura/)

I'm running these from the directory where I ran `force export` from, if I do an `ls` from this directory, I see the folders: `metadata` and `src`.

I'm running these on Mac OS X, `force version` is `v0.22.72`

**Comment by cwarden** [comment]
`force push -t <MetadataType>` should be used, optionally, with `-n <MetadataName>`, not with `-f`.  Alternatively, `-f` can be used with paths (and without `-t` and `-n`).
