### ISSUE TITLE
force login: TCP/lookup issue

### ISSUE THREAD

**Issue by dalefrancum** [ForceCLI/force#418]
I'm getting the following error when trying a "force login" with v0.22.72 of this tool:

```
Post https://login.salesforce.com/services/Soap/u/36.0: dial tcp: lookup login.salesforce.com on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout
ERROR: Post https://login.salesforce.com/services/Soap/u/36.0: dial tcp: lookup login.salesforce.com on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout
```

When I revert to v0.22.67, I don't get the error.

I've tried changing the API version to something other than 36, but from what I understand, you have to be logged into the org first before setting that using "force apiversion".

I'm on a Mac, El Capitan.

**Comment by eddywebs** [comment]
Same problem here...

**Comment by cwarden** [comment]
Looks like an error connecting to your (Google's) name server.
