### ISSUE TITLE
Enhancement: Support Non-bulk record Updates

### ISSUE THREAD

**Issue by isidle** [ForceCLI/force#419]
I would like to be able to perform a DML Update on multiple records without it going through as a bulk-api operation and get a non-zero exit code upon a failure (in traditional batch/shell style).

This would remove the additional complexity is required to check the status of the bulk job repeatedly until the task it complete  (pseudo code below). 

###Currently###
force login
$stdout=`force bulk -c=update -o=account account.csv`
$jobid = getJobId($stdout); 

while ($done==false) {
          $stdout = `force bulk job status $jobid`;

          if (getState($stdout)=='Closed) {
                      done=true;
                      if(Failedrecords($stdout)==0) {
						print('Successful'); exit 0;

					  }
					  else {
						#Send email notification
						exit 1;
					  }
          }
          else {
                   sleep 1; ##Wait a second and try again
          }
}

Method GetState #Process string and return batch job id [Assuming one for sample, but can be multiple]
Method FailedRecords #Process string and return value from "Number of Records Failed"

###Proposed###
force Login
force record update account update.csv --format:csv'
if ($exitCode !=0) {
    ##Something broke, send email notification
}

**Comment by cwarden** [comment]
This is probably best handled through shell scripting or tools like GNU Parallel.
