### ISSUE TITLE
force import reports success on test failures

### ISSUE THREAD

**Issue by floyd-may** [ForceCLI/force#421]
When using `force import -r -l RunLocalTests -c`, I would expect that the force CLI tool would exit with a nonzero exit code if there were any failures. The `import` command appears to ignore anything related to test failures, component deployment problems, e.g. This is based on what I'm seeing for the `DeployResult` object [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deployresult.htm), and the source code [here](https://github.com/ForceCLI/force/blob/master/command/import.go#L141). It seems that the status field on the DeployResult isn't getting checked, and that the only condition that causes the force CLI to exit with a nonzero is if there's some issue decoding the SOAP response.

**Comment by floyd-may** [comment]
Bump. Updated the link to the source code as well.

**Comment by cwarden** [comment]
I've opened #477 to exit with a nonzero error code if there were deployment or test errors when running `force import`.

**Comment by cwarden** [comment]
Fixed in v0.23.0.
