### ISSUE TITLE
Can we run "check-only" push deployment for multiple files?

### ISSUE THREAD

**Issue by MaQ-ITS** [ForceCLI/force#423]
Hi guys,

At first, thanks for great job. 

Can we make validation/check-only/fake deployment (with change reverting) using multiple files?

I'm asking because I'm trying to find a way to achieve fake deploy for multiple classes and pages. Tried using following command:
`force.exe push -r -checkonly src\pages\UploadPhoto.page src\classes\UploadPhoto.cls`

but it seems to only run fake-deploy for first parameter:

> Successes - 2
	UploadPhoto: unchanged         // page file
	UploadPhoto: changed             // class file

Test Successes - 0

Test Failures - 0
The deployment took 8.5464038s to run.

> 

And, in fact, when viewing these files on Salesforce Apex Classes / Pages section, **page** from first parameter doesn't have changed **Last Modified Date** , but **class** file from second parameter is force-deployed (no check-only deployment).

Can we run "check-only" push deployment for multiple files?

**Comment by cwarden** [comment]
`--checkonly` applies to the entire deployment.  Within the org, you'll see it as a validation rather than a deployment.
