### ISSUE TITLE
-bash: go: command not found

### ISSUE THREAD

**Issue by cduncombe44** [ForceCLI/force#43]
Cannot seem to figure out what I am doing wrong.  I apologize as I am aware this a completely Newb question.  Just dying to use this and can't even get it to login.

Using the the code from the hack section and just keep getting the following error

$ export GOPATH=~/go
$ export PATH="$GOPATH/bin:$PATH"
$ export GOPATH=~/go
$ go get -u github.com/heroku/force
-bash: go: command not found

**Comment by Baysah** [comment]
I have the same issue on a windows machine. How do I resolve it?

**Comment by dcarroll** [comment]
Are you trying to compile the source?  If not, you can go to
https://force-cli.herokuapp.com and download the compiled binary.

On Tue, Jan 19, 2016 at 10:14 AM, Baysah <notifications@github.com> wrote:

> I have the same issue on a windows machine. How do I resolve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/43#issuecomment-172938449>.
>



-- 
Thanks,
Dave
