### ISSUE TITLE
Users should be able to disable usage tracking

### ISSUE THREAD

**Issue by ethanfrogers** [ForceCLI/force#435]
We currently use `force` during CI/CD and were hit with a 4 hour period where all of our builds were failing because requests to `https://force-cli.herokuapp.com` were failing. Is there any way this can be removed or disabled via flag?

**Comment by dcarroll** [comment]
I believe that I disabled the usage tracking recently on that website for a different reason.  We were saving off the email address and that looked to violate GDPR requirements.  I may have missed the username/password case.

Will give it a look.

**Comment by cwarden** [comment]
Auth logging was removed in v0.22.77.
