### ISSUE TITLE
Rest Custom Endpoint Support

### ISSUE THREAD

**Issue by dirajkumar** [ForceCLI/force#451]
Hi,

Is there any support to call a custom rest endpoint rather than always assuming we only call the  '/services/data/'? 

Ex: '/services/apexrest/' is a custom endpoint

**Comment by cwarden** [comment]
There isn't, but it would be easy to add.  A couple ideas on how we could expose this.  Any others?

`force rest get -absolute /services/apexrest/myendpoint`

`force rest get -apex /myendpoint`

**Comment by dirajkumar** [comment]
Can we also add the json prettier to the results?

**Comment by dcarroll** [comment]
Have ya tried jq?

**Comment by dirajkumar** [comment]
I haven't tried it. It would be very helpful if you put a couple of examples showing jq and force working together.

**Comment by cwarden** [comment]
For pretty printing output, you can pipe the output to `jq .`, e.g. `force rest get / | jq .`

**Comment by dirajkumar** [comment]
Do you when can we get this feature released?

**Comment by dcarroll** [comment]
pushed new release.

**Comment by dirajkumar** [comment]
@dcarroll What was the solution? I downloaded the new version and it doesn't work. I have tired what @cwarden has suggested. Am I missing something here? And more can please update the examples sections as well?

**Comment by dcarroll** [comment]
`force query "Select Id, Name From Account" --format:json | jq` works fine for me. So should a `rest get`.  Can you provide an example of the command you are attempting?

**Comment by dirajkumar** [comment]
@dcarroll Is it working great with the | jq. Thank you for that. I opened this ticket for an enhancement to support the custom rest endpoint. I don't think that is done yet.

**Comment by dcarroll** [comment]
Ah, ok, sorry. Very hectic few days with the GA launch of Salesforce DX CLI, getting wires crossed. Will re-open.

**Comment by cwarden** [comment]
I've opened #479 to address this.

**Comment by cwarden** [comment]
`force rest` supports the `-absolute` flag as of v0.23.0.
