### ISSUE TITLE
Can not install in Windows 10 (Build 1709)

### ISSUE THREAD

**Issue by twentyTwo** [ForceCLI/force#466]
I have tried several times but it is not installed on Win 10 (Build 1709). A a screen flashes once and then gone.

**Comment by synle** [comment]
Can you provide a screenshot and a small description of how you set up Force CLI? Is this installed within Windows or Windows Bash (Windows Subsystem Linux)?

**Comment by cwarden** [comment]
The application runs from the command line so you need to open a command shell or terminal application, and then run `force` or `force.exe` from the command-line.
