### ISSUE TITLE
Issue with logging in

### ISSUE THREAD

**Issue by forceclihk** [ForceCLI/force#473]
Hi

Running v0.22.25 on Ubuntu.  When I login, I get this output:

**ERROR: <!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%!;(MISSING)
			overflow: hidden;
		  }
		  iframe {
			width: 100%!;(MISSING)
			height: 100%!;(MISSING)
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>**

Subsequent commands seem to cause a crash:

**panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x41e223]

goroutine 16 [running]:
runtime.panic(0x7e3280, 0xa86c33)
	/tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*Force).Query(0x0, 0xc2080366c0, 0x204, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/vendor/lib/go/src/src/github.com/heroku/force/force.go:548 +0x2b3
main.runQuery(0xa85040, 0xc20800e020, 0x1, 0x1)
	/app/vendor/lib/go/src/src/github.com/heroku/force/query.go:39 +0x2ca
main.main()
	/app/vendor/lib/go/src/src/github.com/heroku/force/main.go:50 +0x2aa

goroutine 19 [finalizer wait]:
runtime.park(0x46d580, 0xa8ba80, 0xa89c89)
	/tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa8ba80, 0xa89c89)
	/tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:1445**

**Comment by dcarroll** [comment]
Can you install the latest version and then give it another go?  The CLI is currently on v0.20.84.
