### ISSUE TITLE
Can't perform login

### ISSUE THREAD

**Issue by toretz** [ForceCLI/force#484]
Hi, when launching force login with -i -u -p parameters, i'm getting an error: 

ERROR: mkdir U:: Cannot create a file when that file already exists.

running form a prompt with admin privilege, i get following error:

ERROR: mkdir U:: The system cannot find the path specified.

I'm running from windows 10 and i've admin privilege on the machine. I tried on another laptop with windows 7 enterprise and is working fine, but unfortunately i can't develop on that laptop.

Any clue about the error I receive?
Thanks!

**Comment by cwarden** [comment]
Which version of the force cli are you using, and which shell are you using on Windows 10?

**Comment by toretz** [comment]
Hi, I'm using "regular" cmd, no powershell. I tried several force.com cli version, from 
- https://force-cli.herokuapp.com/
- https://developer.salesforce.com/tools/forcecli (tried both 32 and 64 bit version)

Thanks!
D.

**Comment by cwarden** [comment]
I think the error is probably while saving your session information, most likely because your home directory isn't being found correctly.

If you have the go toolchain set up, I just pushed 540a441fb079440f45a8edc806c3635c2ed27ec1, which might fix the issue.  It uses https://github.com/mitchellh/go-homedir to find the home directory.

Here are windows binaries built from this commit: https://gist.github.com/cwarden/edf9529cca53bcc955dce2ffe29a81ef

**Comment by toretz** [comment]
Hi, after further investigation, i found my homedrive is corrupted. I need to speak with my company IT to have it fixed.
I would say is not a real issue in the tool itself. however, would be an option to specific a different homedrive when running the tool?

Best!
D.

**Comment by cwarden** [comment]
Yes, you can set the `HOMEDRIVE` environment variable (and optionally, `HOMEPATH`).

**Comment by toretz** [comment]
correct, but unfortunately is overridden by my company policy :-(

**Comment by cwarden** [comment]
You can't set any environment variables, or you can't override ones that are already set? (I'm not familiar with what Windows supports in this regard.)

The version in https://github.com/ForceCLI/force/issues/484#issuecomment-360621933 also supports the `HOME` environment variable, which will take precedence over `HOMEDRIVE` and `HOMEPATH`, if set.

**Comment by toretz** [comment]
I can set a new env.var, however there is something coming from my company server which prevails any value i set.
Best!
D.
