### ISSUE TITLE
When deploy aura component the controller and helper are removed

### ISSUE THREAD

**Issue by yurybond** [ForceCLI/force#497]
Hey

I am experiencing an issue with deployment of aura components, for instance it I deploy Lightning Component using the following code:
`force push -f src/aura/MyPowerfulComponent/MyPowerfulComponent.cmp` 
it removes the component controller and helper from salesforce.

**Comment by cwarden** [comment]
Does `force push -t AuraDefinitionBundle -n MyPowerfulComponent` work?

**Comment by yurybond** [comment]
Thank you for merging my pull request. 

By the way 

`force push -t AuraDefinitionBundle -n MyPowerfulComponent `

does not work correctly - it tries to deploy all content of src/aura folder - all aura components
