### ISSUE TITLE
Odd characters when running "force logins"

### ISSUE THREAD

**Issue by samteezy** [ForceCLI/force#519]
See poorly-redacted screenshot below:

![image](https://user-images.githubusercontent.com/879186/39586737-d01e4258-4ec5-11e8-8723-8ce82bbedc52.png)

I'm not sure why this is occurring, it's been doing this for some time on different versions. I just downloaded the latest 64-bit Windows release today.

Let me know if there's other info you need.

**Comment by KThompso** [comment]
These are color codes that aren't being interpreted by your environment.  What are you running this in?  Windows command line?

**Comment by samteezy** [comment]
That's right, Windows 10 command line.

**Comment by KThompso** [comment]
Seems like a [known issue](https://stackoverflow.com/questions/44047988/windows-10-console-colors-not-working-virtual-terminal-control-character-sequen) with newer version of the windows 10 command line.  Not really much to do here unfortunately.
