### ISSUE TITLE
How can I fetch inactive Flow files in Winter 19?

### ISSUE THREAD

**Issue by ericrsmith35** [ForceCLI/force#537]
**force fetch -t Flow** used to fetch all active and inactive flow files.  In Winter 19, Salesforce stopped appending a version # to the end of the Flow filename and the fetch command only retrieves the active version of each Flow.

How can I fetch inactive Flow files in Winter 19?

**Comment by cwarden** [comment]
I don't see anything in the [release notes](https://releasenotes.docs.salesforce.com/en-us/winter19/release-notes/rn_forcecom_flow_fullname.htm?edition=&impact=) indicating how to retrieve versions other than the latest so you might have to use `force apiversion 43.0 && force fetch -t Flow`.

**Comment by ericrsmith35** [comment]
That does work for now.
