### ISSUE TITLE
Cannot download forceCLI using the format u have given

### ISSUE THREAD

**Issue by rgodishela** [ForceCLI/force#542]
rgodishela in ~/Downloads ==>: which go
/usr/local/bin/go
rgodishela in ~/Downloads ==>: go version
go version go1.11.1 darwin/amd64
rgodishela in ~/Downloads ==>: export GOPATH=~/go
rgodishela in ~/Downloads ==>: export PATH="$GOPATH/bin:$PATH"
rgodishela in ~/Downloads ==>: go get -u github.com/ForceCLI/force

**Comment by fernomac** [comment]
Do you get an error message of some kind? I just gave it a shot and it worked for me.

**Comment by rgodishela** [comment]
It was kinda stuck there, should i wait for then certain time?

**Comment by cwarden** [comment]
You can use `-v` with `go get` for verbose output while it downloads and compiles packages.

**Comment by cwarden** [comment]
Use `go install github.com/ForceCLI/force@latest` to install from source with recent version of Go.
