### ISSUE TITLE
`force push -t AuraDefinitionBundle -n <SOME_COMPONENT>` fails, tries to push unrelated metadata

### ISSUE THREAD

**Issue by davidmreed** [ForceCLI/force#547]
ForceCLI version: 0.25.0
OS: GalliumOS (Ubuntu 16.04)

When working on an Aura project, issuing the command
    
    force push -t AuraDefinitionBundle -n <name of component>

yields the following error:

> Validating and deploying push...
> Pushing aura
> Pushing Base
>        Updating Base.cmp ERROR: duplicate value found: AuraDefinitionBundleId duplicates value on record with id: 0Ad16000000XXXX
> %!(EXTRA string=DUPLICATE_VALUE) 

`Base.cmp` is another component in the same project, and is the first component in the project alphabetically; it was not intended to be pushed.

**Comment by cwarden** [comment]
Resolved by #657.
