### ISSUE TITLE
“fatal signup error” when creating scratch org

### ISSUE THREAD

**Issue by matthewholliday** [ForceCLI/force#549]
I have a Dev Hub that is set up in my Developer Edition org. I have been using it for DX development with macOS Mojave v10.14 development for several weeks, but when I tried to create a scratch org today with the same configuration file (see below) on the latest version of the CLI, I received this error in the terminal:

> ERROR: A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance. sfdx-project.json.

The command I am running is:

`sfdx force:org:create -s -f config/project-scratch-def.json -a MyScratchOrg11`

I have re-authenticated with the Dev Hub org to confirm that I had the correct password, but the error persists. The error occurred even after I created a new DX project, created a new Developer Edition org, and re-installed Salesforce DX. These are the contents of the project-scratch-def.json file I am referencing:

```
{
    "orgName": "myCompanyName Company",
    "edition": "Developer",
    "orgPreferences" : {
        "enabled": ["S1DesktopEnabled"]
    }
}
```

**Comment by cwarden** [comment]
Hi @matthewholliday, there is a github repo for the salesforce cli, aka `sfdx`, at https://github.com/forcedotcom/cli-packages, but I think the [Trailblazer Community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1&s1oid=00D300000000iTz&emkind=chatterGroupDigest&s1nid=0DB30000000072L&emtm=1523777343468&s1uid=00530000003TSAc&fromEmail=1&s1ext=0) is still the recommended place to report issues.

If you would like to use the force cli to create a scratch org, this is preliminary support in #446.
