### ISSUE TITLE
Wrong Options Must Throw Error

### ISSUE THREAD

**Issue by miladini** [ForceCLI/force#550]
Hi. I was confused and could not spot the typo in the following command:
force fetch -t=CustomObject n=Contact

there is a hyphen missing before n. So, instead of throwing an error, the tool fetched some other stuff. Could it throw error instead please?

**Comment by easafe** [comment]
This was fixed in https://github.com/ForceCLI/force/releases/tag/v0.27.0 @cwarden

**Comment by cwarden** [comment]
I opened #588 to fix the example in the help output.
