### ISSUE TITLE
queryAll in BULK mode

### ISSUE THREAD

**Issue by KamilZet** [ForceCLI/force#552]
I'm trying to include queryAll option when querying for data in BULK mode. The command I'm executing is:
`force bulk query --all job_list__c "select id from job_list__c limit 10"`
This gives an error.
Am I using the switch --all incorrectly or it's not implemented at all in bulk mode?

**Comment by cwarden** [comment]
queryAll hasn't been added to `force bulk` yet.

**Comment by KamilZet** [comment]
Do you have a plan to implement it in the near (3~4 weeks) future?

**Comment by cwarden** [comment]
I don't, but it should be a small change if you or anyone else wants to submit a pull request.

**Comment by cwarden** [comment]
Addressed in #694
