### ISSUE TITLE
Can i change the batch size when bulk upsert

### ISSUE THREAD

**Issue by haitaoliu507** [ForceCLI/force#579]
Hi,

I'm using force bulk -c=upsert but failed because some batches exceed 10M characters.
Is there a way I can change the batch size so it won't hit that limit?

Thank you!

**Comment by cwarden** [comment]
There's not an option exposed to change the batch size, but it wouldn't be too hard to add.

**Comment by cwarden** [comment]
Opened #635 to add `--batchsize` flag.
