### ISSUE TITLE
lib/log logs everything as error

### ISSUE THREAD

**Issue by BartPeute** [ForceCLI/force#582]
Logs should probably be written to Stdout instead?

In any case, some lines that are logged using this are definitely not errors, for example:
https://github.com/ForceCLI/force/blob/3bb82e9c93f96827f51de8f9c9cb6faca6b82fde/lib/auth.go#L66
https://github.com/ForceCLI/force/blob/3bb82e9c93f96827f51de8f9c9cb6faca6b82fde/lib/auth.go#L208

**Comment by cwarden** [comment]
These are diagnostic or informative messages rather than data returned by the command, so stderr is appropriate although multiple log levels might be useful.  Everything is logged at the Info level right now.
