### ISSUE TITLE
CLI: unexpected end of json input

### ISSUE THREAD

**Issue by leftpropeller** [ForceCLI/force#586]
No matter the command I enter in the force.com CLI on Win10, I always get an error saying "unexpected end of json input", even when just interrogating the version.

Has anyone else come across/resolved this problem?

<img width="355" alt="cli" src="https://user-images.githubusercontent.com/3701767/75172941-ef8fd580-56e2-11ea-8553-caea7dfc64b0.png">

**Comment by cwarden** [comment]
I'm able to reproduce by truncating the json file that stores the current account credentials. Can you check whether that's the problem you're running into?  The credentials are stored in `%HOME%/.force/accounts`, `%USERPROFILE%/.force/accounts` or `%HOMEDRIVE%/.force/accounts` in windows.

**Comment by leftpropeller** [comment]
@cwarden You were spot on!  I do it all in the command line since I log into many orgs, but deleting %USERPROFILE%/.force solved it!

Thank you.
