### ISSUE TITLE
 Add Bulk Data Load 

### ISSUE THREAD

**Issue by dcarroll** [ForceCLI/force#59]
Bulk data loading should be added to the CLI.

**Comment by mickle00** [comment]
Is it a known issue that the `force bulk query retrieve [job id] [batch id] (return the data from the query)` only returns the first result file, and not any subsequent files? It seems like integrating the Bulk API may still be a WIP, so I didn't want to open another issue if this is already known.

**Comment by dcarroll** [comment]
Open the issue, I don't think we have support for multiple result files.
Big gap I think.

On Wed, Feb 18, 2015 at 9:35 AM, mickle00 <notifications@github.com> wrote:

> Is it a known issue that the force bulk query retrieve [job id] [batch
> id] (return the data from the query) only returns the first result file,
> and not any subsequent files? It seems like integrating the Bulk API may
> still be a WIP, so I didn't want to open another issue if this is already
> known.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/59#issuecomment-74908599>.
>



-- 
Thanks,
Dave

**Comment by cwarden** [comment]
Closing this out since bulk api support has been implemented.  We can open new issues for further enhancements or bug fixes.
