### ISSUE TITLE
force:org:create:  A fatal signup error occurred - org creation issue

### ISSUE THREAD

**Issue by patrykacc** [ForceCLI/force#612]
It started to happen today, during scratch org creation I am receiving the following error which is blocker for our development process, take a look pls with urgency, thanks.

Error: 
ERROR running force:org:create:  A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance. 
Try this: 
See https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_signuprequest.htm for information on error code C-9999.

**Comment by cwarden** [comment]
Hi @patrykacc, I think you're looking for https://github.com/salesforcecli/sfdx-cli.
