### ISSUE TITLE
Force Fetch Layouts returning an error but succeeding

### ISSUE THREAD

**Issue by jimpdx** [ForceCLI/force#629]
Force v0.99.0
API Version 55.0
Windows 11 Git Bash

`$ force fetch -t Layout
Not done yet: InProgress  Will check again in five seconds.
You do not have the proper permissions to access Layout.
You do not have the proper permissions to access Layout.
Exported to C:\Users\Jim\Documents\GitHub\xxxxxxx\src`

But then the changes are extracted locally as indicated in the final line of output

**Comment by cwarden** [comment]
It appears to be a metadata API bug related to [custom address fields](https://developer.salesforce.com/docs/atlas.en-us.caf_dev_guide.meta/caf_dev_guide/caf_dev_manage.htm) when fetching the Layouts using the wildcard as of API version 56.0.

Fetching the layouts by name works.
