### ISSUE TITLE
Force Fetch should ignore file extensions and not error out

### ISSUE THREAD

**Issue by jimpdx** [ForceCLI/force#643]
It would be nice if `force fetch` could ignore the file extension and not fail if you happen to still include `.flow` or `.cls` or whatever metadata file extension is used.

```
$ force fetch -t Flow -n New_Financial.flow 
Entity of type 'Flow' named 'New_Financial.flow' cannot be found

$ force fetch -t Flow -n New_Financial (OK)
```

**Comment by cwarden** [comment]
As of #657, `force fetch` can be used with paths, so either `force fetch -t Flow -n New_Financial` or `force fetch src/flows/New_Financial.flow` can be used.
